/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char yytext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, yytext_ptr, yyleng + 1 ); \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 12
#define YY_END_OF_BUFFER 13
static yyconst short int yy_accept[380] =
    {   0,
        0,    0,   13,   12,   12,    7,    7,   11,   11,    8,
        6,    8,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,   11,
       11,    8,    9,   10,   10,   10,   10,   10,   10,   10,
        1,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,    5,
       10,    1,   10,   10,   10,   10,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,    5,
       10,    2,   10,    0,    1,   10,   10,   10,   10,   10,
       10,   10,   10,    0,    5,   10,   10,    0,    0,    1,

        0,    3,   10,   10,    0,    5,   10,    1,    0,    0,
        0,    0,   10,    4,    0,    5,   10,    0,    0,    0,
        0,   10,    0,    5,   10,    0,    1,    0,    0,    1,
        0,    5,   10,    0,    0,    5,   10,    0,    5,   10,
        0,    5,   10,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,

        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,

        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    0,    5,    0,
        5,    0,    5,    0,    5,    0,    5,    5,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    4,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    8,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,   11,
       12,   13,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   23,   24,   25,   26,   27,   28,
       23,   29,   30,   31,   32,   33,   34,   23,   23,   23,
        1,    1,    1,    1,   35,    1,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[36] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[519] =
    {   0,
        0,    0,  749,  750,    0,  750,  738,  750,   27,   26,
      750,  735,   36,  742,   37,   38,   43,   44,   53,   41,
       46,   45,   48,   71,   49,   39,   40,   77,  742,   46,
       73,  750,  750,  740,   57,   59,   80,   82,   84,   86,
      739,   87,   88,   90,   95,   96,   93,   97,   98,  103,
      104,  102,  111,   99,  114,  105,  110,  112,  739,  738,
      736,  735,  734,  129,  116,  131,  118,  133,  135,  134,
      137,  138,  139,  142,  143,  144,  140,  148,  734,  733,
      731,  750,  150,  143,  730,  154,  146,  149,  729,  152,
      151,  163,  171,  729,  728,  726,  172,  715,  696,  723,

      161,  750,  174,  722,  722,  721,  719,  718,  692,  695,
      705,  686,  175,  750,  714,  713,  711,  700,  695,  683,
      686,  181,  707,  706,  704,  691,  750,  692,  687,  700,
      700,  699,  697,  684,  696,  695,  693,  693,  692,  690,
      690,  689,  687,  687,  686,  685,  684,  683,  682,  681,
      680,  679,  678,  677,  676,  675,  674,  673,  672,  671,
      670,  669,  668,  667,  666,  665,  664,  663,  662,  661,
      660,  659,  658,  657,  656,  655,  654,  653,  652,  651,
      650,  649,  648,  647,  646,  645,  644,  643,  642,  641,
      640,  639,  638,  637,  636,  635,  634,  633,  632,  631,

      630,  629,  628,  627,  626,  625,  624,  623,  622,  621,
      620,  619,  618,  617,  616,  615,  614,  613,  612,  611,
      610,  609,  608,  607,  606,  605,  604,  603,  602,  601,
      600,  599,  598,  597,  596,  595,  594,  593,  592,  591,
      590,  589,  588,  587,  586,  585,  583,  580,  577,  574,
      571,  568,  565,  562,  559,  556,  553,  550,  547,  544,
      541,  538,  535,  532,  529,  526,  523,  520,  517,  514,
      511,  508,  505,  502,  499,  496,  493,  490,  487,  484,
      481,  478,  475,  472,  469,  466,  463,  460,  457,  454,
      451,  448,  445,  442,  439,  436,  433,  430,  427,  424,

      421,  418,  415,  412,  409,  406,  403,  400,  397,  394,
      391,  388,  385,  382,  379,  376,  373,  370,  367,  364,
      361,  358,  355,  352,  349,  346,  343,  340,  337,  334,
      331,  328,  325,  322,  319,  316,  313,  310,  307,  304,
      301,  298,  295,  292,  289,  286,  283,  280,  277,  274,
      271,  268,  265,  262,  259,  256,  253,  250,  247,  244,
      241,  238,  235,  232,  229,  226,  223,  220,  217,  214,
      211,  208,  205,  202,  199,  198,  196,  750,  750,  203,
      195,  206,  194,  209,  193,  212,  189,  215,  188,  218,
      187,  221,  185,  224,  183,  227,  181,  230,  180,  233,

       43,  236,  239,  242,  245,  248,  251,  254,  257,  260,
      263,  266,  269,  272,  275,  278,  281,  284,  287,  290,
      293,  296,  299,  302,  305,  308,  311,  314,  317,  320,
      323,  326,  329,  332,  335,  338,  341,  344,  347,  350,
      353,  356,  359,  362,  365,  368,  371,  374,  377,  380,
      383,  386,  389,  392,  395,  398,  401,  404,  407,  410,
      413,  416,  419,  422,  425,  428,  431,  434,  437,  440,
      443,  446,  449,  452,  455,  458,  461,  464,  467,  470,
      473,  476,  479,  482,  485,  488,  491,  494,  497,  500,
      503,  506,  509,  512,  515,  518,  521,  524,  527,  530,

      533,  536,  539,  542,  545,  548,  551,  554,  557,  560,
      563,  566,  569,  572,  575,  578,  581,  584
    } ;

static yyconst short int yy_def[519] =
    {   0,
      379,    1,  379,  379,  380,  379,  379,  379,  379,  379,
      379,  379,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  382,  379,
      379,  379,  379,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  384,  384,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  386,  386,
      387,  379,  387,  379,  387,  387,  387,  387,  387,  387,
      387,  387,  387,  388,  388,  389,  389,  379,  379,  389,

      379,  379,  389,  389,  390,  390,  391,  391,  379,  379,
      379,  379,  391,  379,  392,  392,  393,  379,  379,  379,
      379,  393,  394,  394,  395,  379,  379,  379,  379,  395,
      396,  396,  397,  379,  398,  398,  399,  400,  400,  401,
      402,  402,  379,  403,  403,  404,  404,  405,  405,  406,
      406,  407,  407,  408,  408,  409,  409,  410,  410,  411,
      411,  412,  412,  413,  413,  414,  414,  415,  415,  416,
      416,  417,  417,  418,  418,  419,  419,  420,  420,  421,
      421,  422,  422,  423,  423,  424,  424,  425,  425,  426,
      426,  427,  427,  428,  428,  429,  429,  430,  430,  431,

      431,  432,  432,  433,  433,  434,  434,  435,  435,  436,
      436,  437,  437,  438,  438,  439,  439,  440,  440,  441,
      441,  442,  442,  443,  443,  444,  444,  445,  445,  446,
      446,  447,  447,  448,  448,  449,  449,  450,  450,  451,
      451,  452,  452,  453,  453,  454,  454,  455,  455,  456,
      456,  457,  457,  458,  458,  459,  459,  460,  460,  461,
      461,  462,  462,  463,  463,  464,  464,  465,  465,  466,
      466,  467,  467,  468,  468,  469,  469,  470,  470,  471,
      471,  472,  472,  473,  473,  474,  474,  475,  475,  476,
      476,  477,  477,  478,  478,  479,  479,  480,  480,  481,

      481,  482,  482,  483,  483,  484,  484,  485,  485,  486,
      486,  487,  487,  488,  488,  489,  489,  490,  490,  491,
      491,  492,  492,  493,  493,  494,  494,  495,  495,  496,
      496,  497,  497,  498,  498,  499,  499,  500,  500,  501,
      501,  502,  502,  503,  503,  504,  504,  505,  505,  506,
      506,  507,  507,  508,  508,  509,  509,  510,  510,  511,
      511,  512,  512,  513,  513,  514,  514,  515,  515,  516,
      516,  517,  517,  518,  518,  379,  379,  379,    0,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,

      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,

      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379
    } ;

static yyconst short int yy_nxt[786] =
    {   0,
        4,    4,    5,    4,    6,    7,    7,    6,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   14,   18,
       14,   19,   14,   20,   14,   21,   22,   23,   24,   25,
       26,   14,   27,   28,    4,   31,   31,   32,   32,   33,
       33,   33,   33,   33,   33,  143,   33,   33,   33,   33,
       35,   33,   33,   56,   31,   31,   33,   38,   47,   55,
       33,   36,   33,   39,   41,   37,   42,   40,   43,   45,
       44,   41,   48,   41,   33,   62,   50,   49,   46,   54,
       33,   31,   31,   33,   51,   33,   62,   33,   52,   33,
       33,   33,   53,   33,   57,   62,   33,   58,   33,   33,

       33,   33,   33,   65,   67,   33,   33,   33,   33,   64,
       63,   71,   69,   33,   33,   33,   66,   33,   62,   33,
       68,   33,   72,   70,   73,   75,   62,   62,   62,   62,
       74,   76,   33,   78,   33,   77,   33,   33,   33,   86,
       33,   33,   33,   33,   83,   33,   33,   33,   85,   33,
       84,   33,   33,   33,   33,   33,   85,   33,   98,   85,
       87,   90,   92,   97,   91,   88,   33,   89,   99,   85,
       85,   93,  100,  103,   33,   33,  111,   33,   33,  100,
      101,  100,  140,  137,   33,  133,  112,  125,  100,  117,
      107,   96,  122,  104,  130,   81,   61,   34,  378,  113,

      378,  377,  108,   29,  377,   29,   59,  375,   59,   79,
      375,   79,   94,  373,   94,  105,  373,  105,  115,  371,
      115,  123,  371,  123,  131,  369,  131,  135,  369,  135,
      138,  367,  138,  141,  367,  141,  144,  365,  144,  146,
      365,  146,  148,  363,  148,  150,  363,  150,  152,  361,
      152,  154,  361,  154,  156,  359,  156,  158,  359,  158,
      160,  357,  160,  162,  357,  162,  164,  355,  164,  166,
      355,  166,  168,  353,  168,  170,  353,  170,  172,  351,
      172,  174,  351,  174,  176,  349,  176,  178,  349,  178,
      180,  347,  180,  182,  347,  182,  184,  345,  184,  186,

      345,  186,  188,  343,  188,  190,  343,  190,  192,  341,
      192,  194,  341,  194,  196,  339,  196,  198,  339,  198,
      200,  337,  200,  202,  337,  202,  204,  335,  204,  206,
      335,  206,  208,  333,  208,  210,  333,  210,  212,  331,
      212,  214,  331,  214,  216,  329,  216,  218,  329,  218,
      220,  327,  220,  222,  327,  222,  224,  325,  224,  226,
      325,  226,  228,  323,  228,  230,  323,  230,  232,  321,
      232,  234,  321,  234,  236,  319,  236,  238,  319,  238,
      240,  317,  240,  242,  317,  242,  244,  315,  244,  246,
      315,  246,  248,  313,  248,  250,  313,  250,  252,  311,

      252,  254,  311,  254,  256,  309,  256,  258,  309,  258,
      260,  307,  260,  262,  307,  262,  264,  305,  264,  266,
      305,  266,  268,  303,  268,  270,  303,  270,  272,  301,
      272,  274,  301,  274,  276,  299,  276,  278,  299,  278,
      280,  297,  280,  282,  297,  282,  284,  295,  284,  286,
      295,  286,  288,  293,  288,  290,  293,  290,  292,  291,
      292,  294,  291,  294,  296,  289,  296,  298,  289,  298,
      300,  287,  300,  302,  287,  302,  304,  285,  304,  306,
      285,  306,  308,  283,  308,  310,  283,  310,  312,  281,
      312,  314,  281,  314,  316,  279,  316,  318,  279,  318,

      320,  277,  320,  322,  277,  322,  324,  275,  324,  326,
      275,  326,  328,  273,  328,  330,  273,  330,  332,  271,
      332,  334,  271,  334,  336,  269,  336,  338,  269,  338,
      340,  267,  340,  342,  267,  342,  344,  265,  344,  346,
      265,  346,  348,  263,  348,  350,  263,  350,  352,  261,
      352,  354,  261,  354,  356,  259,  356,  358,  259,  358,
      360,  257,  360,  362,  257,  362,  364,  255,  364,  366,
      255,  366,  368,  253,  368,  370,  253,  370,  372,  251,
      372,  374,  251,  374,  376,  249,  376,  249,  247,  247,
      245,  245,  243,  243,  241,  241,  239,  239,  237,  237,

      235,  235,  233,  233,  231,  231,  229,  229,  227,  227,
      225,  225,  223,  223,  221,  221,  219,  219,  217,  217,
      215,  215,  213,  213,  211,  211,  209,  209,  207,  207,
      205,  205,  203,  203,  201,  201,  199,  199,  197,  197,
      195,  195,  193,  193,  191,  191,  189,  189,  187,  187,
      185,  185,  183,  183,  181,  181,  179,  179,  177,  177,
      175,  175,  173,  173,  171,  171,  169,  169,  167,  167,
      165,  165,  163,  163,  161,  161,  159,  159,  157,  157,
      155,  155,  153,  153,  151,  151,  149,  149,  147,  147,
       33,  145,  145,   33,  142,  142,   33,  139,  139,  127,

       33,  136,  136,   33,  127,  134,  127,   33,  132,  132,
      129,  128,  127,  126,   33,  124,  124,  121,  120,  119,
      118,   33,   33,  116,  116,  114,   33,  110,  109,   33,
      106,  106,  102,   33,   33,   95,   95,   82,   33,   33,
       80,   80,   33,   33,   60,   33,   32,   30,  379,    3,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379
    } ;

static yyconst short int yy_chk[786] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    9,    9,   10,   10,   13,
       15,   16,   26,   27,   20,  401,   17,   18,   22,   21,
       13,   23,   25,   27,   30,   30,   19,   15,   20,   26,
       35,   13,   36,   15,   16,   13,   17,   15,   17,   19,
       18,   19,   21,   22,   24,   36,   23,   21,   19,   25,
       28,   31,   31,   37,   24,   38,   35,   39,   24,   40,
       42,   43,   24,   44,   28,   37,   47,   28,   45,   46,

       48,   49,   54,   40,   43,   52,   50,   51,   56,   39,
       38,   47,   45,   57,   53,   58,   42,   55,   47,   65,
       44,   67,   49,   46,   50,   54,   52,   48,   56,   51,
       53,   55,   64,   58,   66,   57,   68,   70,   69,   67,
       71,   72,   73,   77,   64,   74,   75,   76,   66,   87,
       65,   78,   88,   83,   91,   90,   77,   86,   84,   68,
       69,   72,   74,   83,   73,   70,   92,   71,   84,   76,
       75,   78,   86,   90,   93,   97,  101,  103,  113,   88,
       87,   91,  399,  397,  122,  395,  101,  393,   93,  391,
      389,  387,  113,   92,  122,  385,  383,  381,  377,  103,

      376,  375,   97,  380,  374,  380,  382,  373,  382,  384,
      372,  384,  386,  371,  386,  388,  370,  388,  390,  369,
      390,  392,  368,  392,  394,  367,  394,  396,  366,  396,
      398,  365,  398,  400,  364,  400,  402,  363,  402,  403,
      362,  403,  404,  361,  404,  405,  360,  405,  406,  359,
      406,  407,  358,  407,  408,  357,  408,  409,  356,  409,
      410,  355,  410,  411,  354,  411,  412,  353,  412,  413,
      352,  413,  414,  351,  414,  415,  350,  415,  416,  349,
      416,  417,  348,  417,  418,  347,  418,  419,  346,  419,
      420,  345,  420,  421,  344,  421,  422,  343,  422,  423,

      342,  423,  424,  341,  424,  425,  340,  425,  426,  339,
      426,  427,  338,  427,  428,  337,  428,  429,  336,  429,
      430,  335,  430,  431,  334,  431,  432,  333,  432,  433,
      332,  433,  434,  331,  434,  435,  330,  435,  436,  329,
      436,  437,  328,  437,  438,  327,  438,  439,  326,  439,
      440,  325,  440,  441,  324,  441,  442,  323,  442,  443,
      322,  443,  444,  321,  444,  445,  320,  445,  446,  319,
      446,  447,  318,  447,  448,  317,  448,  449,  316,  449,
      450,  315,  450,  451,  314,  451,  452,  313,  452,  453,
      312,  453,  454,  311,  454,  455,  310,  455,  456,  309,

      456,  457,  308,  457,  458,  307,  458,  459,  306,  459,
      460,  305,  460,  461,  304,  461,  462,  303,  462,  463,
      302,  463,  464,  301,  464,  465,  300,  465,  466,  299,
      466,  467,  298,  467,  468,  297,  468,  469,  296,  469,
      470,  295,  470,  471,  294,  471,  472,  293,  472,  473,
      292,  473,  474,  291,  474,  475,  290,  475,  476,  289,
      476,  477,  288,  477,  478,  287,  478,  479,  286,  479,
      480,  285,  480,  481,  284,  481,  482,  283,  482,  483,
      282,  483,  484,  281,  484,  485,  280,  485,  486,  279,
      486,  487,  278,  487,  488,  277,  488,  489,  276,  489,

      490,  275,  490,  491,  274,  491,  492,  273,  492,  493,
      272,  493,  494,  271,  494,  495,  270,  495,  496,  269,
      496,  497,  268,  497,  498,  267,  498,  499,  266,  499,
      500,  265,  500,  501,  264,  501,  502,  263,  502,  503,
      262,  503,  504,  261,  504,  505,  260,  505,  506,  259,
      506,  507,  258,  507,  508,  257,  508,  509,  256,  509,
      510,  255,  510,  511,  254,  511,  512,  253,  512,  513,
      252,  513,  514,  251,  514,  515,  250,  515,  516,  249,
      516,  517,  248,  517,  518,  247,  518,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,

      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  134,

      133,  132,  131,  130,  129,  128,  126,  125,  124,  123,
      121,  120,  119,  118,  117,  116,  115,  112,  111,  110,
      109,  108,  107,  106,  105,  104,  100,   99,   98,   96,
       95,   94,   89,   85,   81,   80,   79,   63,   62,   61,
       60,   59,   41,   34,   29,   14,   12,    7,    3,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "lexico.l"
#define INITIAL 0
#line 2 "lexico.l"

#include <stdio.h>
#include <stdio.h>
#include <string.h>


#line 706 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 26 "lexico.l"


#line 860 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 380 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 750 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "lexico.l"
{fprintf(yyout,"%s",yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "lexico.l"
{fprintf(yyout,"CHAR");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "lexico.l"
{fprintf(yyout,"LEFT");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "lexico.l"
{fprintf(yyout,"RIGHT");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "lexico.l"
{fprintf(yyout,"STRING");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "lexico.l"
{fprintf(yyout,"ASIGNACION");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "lexico.l"
{fprintf(yyout,"ARITMETICO");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "lexico.l"
{fprintf(yyout,"RELACIONAL");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "lexico.l"
{fprintf(yyout,"IDENTIFICADOR");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "lexico.l"
{fprintf(yyout,"IDENTIFICADOR");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "lexico.l"
{
	if(atoi(yytext)<-32768 || atoi(yytext)>32767){
		fprintf(yyout,"%s",yytext);
	}else{
		fprintf(yyout,"ENTERO");
	}
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "lexico.l"
ECHO;
	YY_BREAK
#line 1009 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 380 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 380 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 379);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 45 "lexico.l"


int main(argc, argv)
int argc;
char **argv;
{
	if(argc <= 2){
		printf("Error: Faltan par%cmetros en la l%cnea de comandos.\nUso: lexico.exe archivo_entrada archivo_salida",160,161);
		return 0;
	}
	else if(argc > 3){
		printf("Error: Demaciados par%cmetros en la l%cnea de comandos.\nUso: lexico.exe archivo_entrada archivo_salida",160,161);
		return 0;
	}else{
		yyin =fopen(argv[1],"r");
		yyout =fopen(argv[2],"r");
		if(yyin == NULL){
			printf("Error: El archivo de entrada no existe.");
			fclose(yyin);
			fclose(yyout);
			return 0;
		}else if(yyout!=NULL){
			printf("Error: El archivo de salida ya existe.");
			fclose(yyin);
			fclose(yyout);
			return 0;
		}
	}
	yyin=stdin;
	yyin =fopen(argv[1],"r");
	yyout =fopen(argv[2],"w");
	yylex();
	fclose(yyin);
	fclose(yyout);	
    return 0;
}
  

